version: '3.4'

services:

  flower:
    command: celery -A app flower --loglevel=INFO
    environment:
      # - CELERY_BROKER_URL=amqp://guest:guest@broker//
      - BROKER_URL=amqp://guest:guest@broker//
      - FLOWER_UNAUTHENTICATED_API=true
    # image: mher/flower
    image: worker
    ports:
      - 5555:5555

  rabbitmq:
    hostname: broker
    image: rabbitmq
    ports:
      - 5672:5672

  worker:
    build: .
    command: celery -A app worker --loglevel=INFO
    environment:
      - BROKER_URL=amqp://guest:guest@broker//
    image: worker
