version: '3.4'

services:

  flower:
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@broker//
      - FLOWER_PORT=8888
    image: mher/flower
    ports:
      - 8888:8888

  rabbitmq:
    hostname: broker
    image: rabbitmq
    ports:
      - 5672:5672

  worker:
    build: .
    command: celery --app=app worker --loglevel=INFO
    environment:
      - BROKER_URL=amqp://guest:guest@broker//
    image: worker
